### PR TITLE
News-week-clone

### PR DESCRIPTION
**Pull request by evabanegacom**
This is a solo project about building a responsive webpage design

It was done to identify dimension break points and responsiveness with respect to

different screen sizes.

It is a replica of newsweek.com

### CODE REVIEW

**Comment by davidmrtz-dev** [comment]
## Hi @evabanegacom  . 👨‍🚀  
### Very good job so far.
* Your README file is clear and descriptive.
* Commits are ok, clear and easy to read.
However, the following issues need to be implemented/fixed to consider this project as approved  👨‍💻  ⬇️ 

****
- [ ] Latest news section.
You work is great in this section and is almost done, there's a couple of issues to solve.
As is required on this project ➡️  "In this project students are asked to be more precise and to make sure that their page looks exactly the same as the source page."
So let's add some spacing  between the image and the text, like in the original page:
How it looks now. ⬇️ 

Screen Shot 2020-04-07 at 7 31 41 PM


The example on which the project is based. ⬇️ 

Screen Shot 2020-04-07 at 7 31 54 PM

****
- [ ] More stories.
There are some small differences between your project and the given page, please modify the sizes of the titles, text and align them so that it looks according to the given page.
This in order that your page looks as much as possible to the example given and looks very professional.
How it looks now. ⬇️ 
Screen Shot 2020-04-07 at 7 36 14 PM

The example on which the project is based. ⬇️ 
Screen Shot 2020-04-07 at 7 36 37 PM

****
- [ ] Spacing between Featured Stories.
This section looks great! but we can improve it! 
Add the spacing between the elements.
Descriptive images below.
How it looks now. ⬇️ 
Screen Shot 2020-04-07 at 7 42 24 PM

The example on which the project is based. ⬇️ 
Screen Shot 2020-04-07 at 7 42 30 PM
****
- [ ] HTML Validator.
Kindly fix the errors that are informing the HTML Validator.
Screen Shot 2020-04-07 at 7 44 32 PM

****
- [ ] Inline Styling.
There's nor allowed the use of inline-styling because it's considered a bad practice.
Heres a [link](https://speckyboy.com/good-bad-css-practices) with more information about that.
Screen Shot 2020-04-07 at 7 45 45 PM
****
- [ ] Pull Request has a meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
Kindly add a short descirptions of what you did on this project also you can a list with 3 or 4 points 😄 
****

### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. ♻️  👀 
****

Happy coding! 😄 💻  


**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Comment by evabanegacom** [comment]
I have fixed it, I think the problem was that i opened the pull request on the master branch

**Comment by mikenath223** [comment]
**Pull request currently under review by Michgolden Ukeje (TSE).**
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi @evabanegacom  👋

However, there are a few changes to be met:

- [ ] Required - Kindly update your pull request message to reflect the work you've done on this project. No need to close the pull request simply edit the message.

- [ ] Required - Also do ensure you structure your files into descriptive folders. `styles/` for CSS and `images/` fro image files.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by evabanegacom** [comment]
This is a bootstrap project
I used bootstrap and css but mainly bootstrap for the project
created a clone of the news week web-page

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi again @evabanegacom 👋

You've done quite well fixing one of the issues referenced in the previous review.

However,

- [ ] Required - Kindly update your pull request message with a descriptive title. Simply click the icon at the top of this pull request to do that. Its circled in red the [Screenshot]👇
Inkedice_screenshot_20200408-112011_LI

Kindly fix these issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAVE A SMASHING CODING DAY👌✅

**Comment by evabanegacom** [comment]
This is a solo project about building a responsive webpage design

It was done to identify dimension break points and responsiveness with respect to 

different screen sizes.

It is a replica of newsweek.com

**Comment by evabanegacom** [comment]
how far

**Comment by sumancrest0001** [comment]
Congratulation @evabanegacom  It's a yes from my side. You have done a great job. :+1: :+1: 

[TIPS] In your pull request, you can add or describe features that you added or issues that you fixed instead of just describing the whole project goals. Please read this [article](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) from the Microverse curriculum. It will be helpful for future works. 
mission

### All the best with the next project and don't forget to merge this branch to master.
Happy Coding

**Comment by evabanegacom** [comment]
Yeah i will thanks

**Pull request merged**
